### PR TITLE
Xylus Bug Fixes

### PR DESCRIPTION
**Pull request by XylusChen**

### CODE REVIEW

**Comment by XylusChen** [comment]
Add tag prefix for add application command format. Closes #181

**Comment by XylusChen** [comment]
Update error message for invalid Tag input. Closes #221.

**Comment by XylusChen** [comment]
Fix bug where application would crash on start-up if duplicate entries inserted directly into data file. Closes #218.

**Review by noahxinjie — APPROVED** [review]
LGTM! Great job!

**Pull request merged**
